auth:
    resource: '../src/Authenticator/Controller/'
    type: annotation
    name_prefix: 'auth_'
surveys:
    resource: '../src/Survey/Api/'
    type: annotation
    prefix: '/api'
    name_prefix: 'surveys_'
