auth:
    resource: '../src/Authenticator/Controller/'
    type: attribute
    name_prefix: 'auth_'
survey_api:
    resource: '../src/Survey/Api/'
    type: attribute
    prefix: '/api'
surveys:
    resource: '../src/Survey/Controller/'
    type: attribute
site:
    resource: '../src/Site/Controller/'
    type: attribute
    name_prefix: 'site_'
